version: "3.9"

services:
    app:
        build: .
        image: phearunum/laravel-api:latest
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            - "9000:80" # Expose PHP-FPM port if needed
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: base64:WZ9qYrj8+3gKlzJp7PcM7c3RFVXt3PZxJDFUluywZcE=
            DB_CONNECTION: mysql
            DB_HOST: xxxx
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: laravel
            DB_PASSWORD: P@ssw0rd
